"""
Fetches top Claude/Anthropic articles from free RSS feeds and saves a
dated Markdown digest to article/YYYY-MM-DD.md.

No API key required — uses Google News RSS and Hacker News search.
"""

import os
import sys
import datetime
import textwrap
from urllib.parse import quote

import feedparser
import requests

QUERIES = [
    "Anthropic Claude",
    "Claude AI model",
    "Anthropic AI",
]

GOOGLE_NEWS_RSS = "https://news.google.com/rss/search?q={query}&hl=en-US&gl=US&ceid=US:en"
HN_SEARCH = "https://hn.algolia.com/api/v1/search?query={query}&tags=story&numericFilters=created_at_i>{since}"

MAX_ARTICLES = 10


def fetch_google_news(query: str) -> list[dict]:
    url = GOOGLE_NEWS_RSS.format(query=quote(query))
    feed = feedparser.parse(url)
    results = []
    for entry in feed.entries:
        results.append({
            "title": entry.get("title", "").split(" - ")[0].strip(),
            "source": entry.get("source", {}).get("title", "Google News"),
            "url": entry.get("link", ""),
            "summary": entry.get("summary", "")[:200],
        })
    return results


def fetch_hn(query: str, since_ts: int) -> list[dict]:
    url = HN_SEARCH.format(query=quote(query), since=since_ts)
    try:
        resp = requests.get(url, timeout=10)
        resp.raise_for_status()
        hits = resp.json().get("hits", [])
    except Exception:
        return []
    return [
        {
            "title": h.get("title", ""),
            "source": "Hacker News",
            "url": h.get("url") or f"https://news.ycombinator.com/item?id={h.get('objectID')}",
            "summary": f"HN discussion — {h.get('points', 0)} points, {h.get('num_comments', 0)} comments",
        }
        for h in hits
        if h.get("title")
    ]


def deduplicate(articles: list[dict]) -> list[dict]:
    seen_urls: set[str] = set()
    seen_titles: set[str] = set()
    out = []
    for a in articles:
        url = a["url"].split("?")[0].rstrip("/")
        title_key = a["title"].lower()[:60]
        if url in seen_urls or title_key in seen_titles:
            continue
        seen_urls.add(url)
        seen_titles.add(title_key)
        out.append(a)
    return out


def build_markdown(date_str: str, articles: list[dict]) -> str:
    lines = [
        f"# Claude Articles — {date_str}",
        "",
        "> Auto-generated by /daily-claude-article-search",
        "",
        "## Top Articles",
        "",
    ]
    for i, a in enumerate(articles, 1):
        summary = textwrap.shorten(a["summary"], width=200, placeholder="...")
        lines += [
            f"### {i}. {a['title']}",
            f"- **Source**: {a['source']}",
            f"- **URL**: {a['url']}",
            f"- **Summary**: {summary}",
            "",
        ]
    return "\n".join(lines)


def main() -> None:
    date_override = os.environ.get("DATE_OVERRIDE", "").strip()
    if date_override:
        target_date = datetime.date.fromisoformat(date_override)
    else:
        target_date = datetime.date.today()

    date_str = target_date.isoformat()
    since_ts = int(
        datetime.datetime.combine(target_date - datetime.timedelta(days=1), datetime.time.min).timestamp()
    )

    all_articles: list[dict] = []
    for query in QUERIES:
        all_articles.extend(fetch_google_news(query))
        all_articles.extend(fetch_hn(query, since_ts))

    articles = deduplicate(all_articles)[:MAX_ARTICLES]

    if not articles:
        print("No articles found — skipping file write.")
        sys.exit(0)

    os.makedirs("article", exist_ok=True)
    out_path = f"article/{date_str}.md"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(build_markdown(date_str, articles))

    print(f"Saved {len(articles)} articles to {out_path}")


if __name__ == "__main__":
    main()
